all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: aws.pem
    service_subnet: "10.95.0.0/12"
    pod_subnet: "10.244.0.0/16"
  hosts:
    master:
      ansible_host: 10.1.15.177
    workers:
      worker1:
        ansible_host: 10.1.1.243
      worker2:
        ansible_host: 10.1.0.159